services:
  robot-base:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: robot-base
    network_mode: host
    privileged: true # required for imu

  robot-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: robot-dev
    network_mode: host
    privileged: true # required for imu
    tty: true
    stdin_open: true
    volumes:
      - ./src/robot:/robot_ws/src/robot:rw
